import './scripts/first-slide'
import './css/main.css'
import './sass/main.scss'
import 'normalize.css'
import './sass/_variables.scss'
import './sass/_mixins.scss'
import './sass/first-slide.scss'
import './sass/second-slide.scss'
import './sass/third-slide.scss'
import './sass/third-slide-navigation.scss'
import './sass/third-slide-first.scss'

